# Generated by Django 5.1.6 on 2025-02-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Bad', 'Bad')], max_length=50),
        ),
    ]
